import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'injection.config.dart';

final getIt = GetIt.instance;

/// Same entry point as starterflutter-develop.
///
/// The `injection.config.dart` sibling is normally generated by build_runner:
///   flutter pub run build_runner build --delete-conflicting-outputs
/// A hand-written version is shipped so the project compiles out-of-the-box;
/// re-running build_runner after adding new @injectable classes will
/// regenerate it.
@InjectableInit()
Future<GetIt> configureDependencies() => getIt.init();
